https://discourse.onlinedegree.iitm.ac.in/t/164277

Specially after the release of the sessions… Whole day and night have gone like nothing, infront of the computer…<br/>
Plz sir understand the situation and extend the deadline…</p><hr>

<h4>sarvan108 (#369)</h4>
<p>How to resolve this?<br/>
sarvan108@SURIYA:/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro$ uv run app.py<br/>
Traceback (most recent call last):<br/>
File “/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro/app.py”, line 10, in <br/>
from fastapi import FastAPI<br/>
ModuleNotFoundError: No module named ‘fastapi’<br/>
sarvan108@SURIYA:/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro$ pip show fastapi<br/>
WARNING: Package(s) not found: fastapi<br/>
sarvan108@SURIYA:/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro$ pip install fastapi<br/>
error: externally-managed-environment</p>
<p>× This environment is externally managed<br/>
╰─&gt; To install Python packages system-wide, try apt install<br/>
python3-xyz, where xyz is the package you are trying to<br/>
install.</p>
<pre><code>If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.