https://discourse.onlinedegree.iitm.ac.in/t/171141

<a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/jivraj">@Jivraj</a></p><hr>

<h4>22f3000819 (#114)</h4>
<p><a class="mention" href="/u/carlton">@carlton</a><br/>
My docker logs shows that <code>OSError: Cannot find resource</code> error occurred when the data generation script tried to access font files in generation for a8.<br/>
<div class="lightbox-wrapper"><a class="lightbox" data-download-href="/uploads/short-url/vVy1Zl2FILIE7YmcgLMAd1engpp.png?dl=1" href="https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/d/f/dfc4c289dcc2ddda315bd9f97a9ff21c166792af.png" rel="noopener nofollow ugc" title="image"><div class="meta"><svg aria-hidden="true" class="fa d-icon d-icon-far-image svg-icon"><use href="#far-image"></use></svg><span class="filename">image</span><span class="informations">1485Ã—807 37.4 KB</span><svg aria-hidden="true" class="fa d-icon d-icon-discourse-expand svg-icon"><use href="#discourse-expand"></use></svg></div></a></div></p>
<p>The datagen.py script looked for Arial font in the try block and when it encountered error it went to the except block to use DejaVuSans, the Pillow default, except it encountered the same error there, which was not handled.