https://discourse.onlinedegree.iitm.ac.in/t/171141

We will ONLY consider this as valid.</p>
<p>2/16/2025 9:30:05	23f1001156@ds.study.iitm.ac.in	<a class="inline-onebox" href="https://github.com/Rohit23f1001156/project1_tds">GitHub - Rohit23f1001156/project1_tds</a>	rohit23f1001156/project1_tds</p><hr>

<h4>ROHIT_B_LAKSHMANAN (#54)</h4>
<p>This is the id of the docker image that was evaluated: 468630ef32b8<br/>
I believe this is not my docker ID that was submitted, my docker ID is “bd2d0e570ec6”:</p>
<p>proof:<br/>
REPOSITORY                           TAG          DIGEST                                                                    IMAGE ID       CREATED        SIZE<br/>
rohit23f1001156/project1_tds         v3           sha256:bd2d0e570ec6b9a4a2b1565602a7c6abd118c4df06ca39e9dd78b0c06cab7542   bd2d0e570ec6   5 weeks ago    816MB</p>
<p>Please, look over it.</p>
<p>Also, in my docker log file, it is showing the error as:<br/>
<div class="lightbox-wrapper"><a class="lightbox" data-download-href="/uploads/short-url/ldBEby0LkRjZoaTLvE4vhz7dhA5.png?dl=1" href="https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/9/4/94b76c5b49a749a2750e840d06fef2715c0b0b69.png" rel="noopener nofollow ugc" title="Screenshot 2025-03-29 at 11.10.03 AM"><div class="meta"><svg aria-hidden="true" class="fa d-icon d-icon-far-image svg-icon"><use href="#far-image"></use></svg><span class="filename">Screenshot 2025-03-29 at 11.10.03 AM</span><span class="informations">2360×1582 503 KB</span><svg aria-hidden="true" class="fa d-icon d-icon-discourse-expand svg-icon"><use href="#discourse-expand"></use></svg></div></a></div></p>
<p>what is the reason for this?<br/>
It was running properly before, please help.</p>
<p>Regards,<br/>
Rohit<br/>
23f1001156</p>
<p><a class="mention" href="/u/jivraj">@Jivraj</a> <a class="mention" href="/u/carlton">@carlton</a></p><hr>

<h4>23f1000598 (#53)</h4>
<p>yaa same issue i am also facing ,<br/>
and this LLM thing is very new for us , and we tried our best to complete.