https://discourse.onlinedegree.iitm.ac.in/t/171141

Can you please re-evaluate by enclosing each of the data generation function calls in their own try-except blocks?<br/>
<div class="lightbox-wrapper"><a class="lightbox" data-download-href="/uploads/short-url/eQVQww2TLZd4V84EezSUFxCArFA.png?dl=1" href="https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/6/8/681a3a02c951eaf7014d116d45b9ac35b8fdd2de.png" rel="noopener nofollow ugc" title="image"><div class="meta"><svg aria-hidden="true" class="fa d-icon d-icon-far-image svg-icon"><use href="#far-image"></use></svg><span class="filename">image</span><span class="informations">302Ã—252 3.45 KB</span><svg aria-hidden="true" class="fa d-icon d-icon-discourse-expand svg-icon"><use href="#discourse-expand"></use></svg></div></a></div><br/>
I think it would be better to enclose each of these function calls in their own try-except blocks.